name: python2-jamesh
version: 2.7.13
summary: Python language interpreter and standard library
description: |
  Python is a programming language that lets you work quickly and
  integrate systems more effectively.

grade: devel
confinement: strict

slots:
  python2:
    interface: content
    content: python2
    read:
      - .

apps:
  python:
    command: bin/python
    aliases:
      - python
      - python2
      - python2.7
  pydoc:
    command: bin/python -m pydoc
    aliases:
      - pydoc
      - pydoc2.7
  pip:
    command: bin/python -m pip
    aliases:
      - pip
      - pip2
      - pip2.7

parts:
  compiler-wrapper:
    plugin: nil
    source: tools
    install: |
      sed -e "s/@CC@/${CC:-gcc}/g" \
          -e "s/@TRIPLET@/$(dpkg-architecture -q DEB_TARGET_MULTIARCH)/g" \
          compiler.sh.in > $SNAPCRAFT_PART_INSTALL/compiler.sh
      chmod a+x $SNAPCRAFT_PART_INSTALL/compiler.sh
    prime:
      - -*
    build-packages:
      - gcc
      - dpkg-dev

  python:
    after:
      - compiler-wrapper
    plugin: autotools
    source: https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz
    configflags:
      - --enable-shared
      - --enable-ipv6
      - --enable-unicode=ucs4
      #- --enable-loadable-sqlite-extensions
      - --with-dbmliborder=bdb:gdbm
      - --with-computed-gotos
      - --with-ensurepip=upgrade
      - --with-system-expat
      - --with-system-ffi
      - --with-fpectl
    make-parameters:
      - CC=$SNAPCRAFT_STAGE/compiler.sh

    filesets:
      python:
        - bin/
        - lib/
        - -bin/*-config
        - -lib/python2.7/test/
        - -lib/python2.7/*/test/
        - -lib/python2.7/*/tests/
        - -lib/python2.7/idle/idle_test/
        - -lib/python2.7/lib-dynload/_*test*.so
        - -lib/pkgconfig
      tests:
        - lib/python2.7/test/
        - lib/python2.7/*/test/
        - lib/python2.7/*/tests/
        - lib/python2.7/idle/idle_test/
        - lib/python2.7/lib-dynload/_*test*.so
      manpages:
        - share/man/
      dev:
        - bin/*-config
        - include/
        - lib/pkgconfig/

    prime:
      - $python
      - $manpages
      - $dev

    build-packages:
      - gcc
      - libreadline-dev
      - libtinfo-dev
      - libncursesw5-dev
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev
      - libgdbm-dev
      - libdb-dev
      - libssl-dev
      - libexpat1-dev
      - libmpdec-dev
      - libbluetooth-dev
      - libsqlite3-dev
      - libffi-dev

  sitecustomize:
    after:
      - python
    plugin: dump
    source: src
    organize:
      '*': lib/python2.7/site-packages/

    install: |
      set -x
      # byte compile sitecustomize.py
      installdir=$SNAPCRAFT_PART_INSTALL
      primedir=lib/python2.7/site-packages
      $SNAPCRAFT_STAGE/bin/python2.7 -Wi -m compileall -d $primedir $installdir
      $SNAPCRAFT_STAGE/bin/python2.7 -O -Wi -m compileall -d $primedir $installdir
      $SNAPCRAFT_STAGE/bin/python2.7 -OO -Wi -m compileall -d $primedir $installdir

